{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "ssh-service-hostkeys"
  labels:
    app.kubernetes.io/name: {{ include "ssh-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
{{ include "ssh-service.ssh-hostkeys" . | nindent 2 }}

{{- end -}}
