{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssh-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ssh-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  passwd: {{ include "ssh-service.passwd" . | b64enc | quote }}
  shadow: {{ include "ssh-service.shadow" . | b64enc | quote }}
{{- end -}}
