{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "ssh-service.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ include "ssh-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  sshd_config: >
  {{ include "ssh-service.sshd_config" . | nindent 4 }}

  user_config: >
  {{ toPrettyJson .Values.userConfig | nindent 4 }}

  tcp_wrappers: >
  {{ include "ssh-service.tcp_wrappers" . | nindent 4 }}

  motd: >
  {{ default (printf "\n\n\nWarning: All volumes are volatile! Please do not store your files here!\n\n") .Values.motdContent }}

{{- end }}
