{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-service.fullname" . }}
  labels:
{{ include "ssh-service.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: {{ include "ssh-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges:
{{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
{{- end -}}
{{- end -}}
