#!/usr/bin/env bash
HOMEDIR="/home/${PAM_USER}"

if [ ! -d "$HOMEDIR" ] ; then
    mkdir -p "$HOMEDIR"

    if [ -d "/etc/users/${PAM_USER}" ] ; then
	find "/etc/users/${PAM_USER}" -type f -exec cp {} "$HOMEDIR" \;
    else
	find "/etc/users/default" -type f -exec cp {} "$HOMEDIR" \;
    fi
fi

echo "Homedir for ${PAM_USER} created as ${HOMEDIR}"
