name: Helm Publish

on:
  push:
    tags:
    - '*'
    branches: 
    - master

  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.CR_PAT }}
